config/routes.rb
Rails.application.routes.draw do
  devise_for :administrators, :controllers =>{
    :registrations => 'administrators/registrations',
    :sessions => 'administrators/sessions'
  }
  devise_scope :administrator do
    get "sign_in", :to => "administrators/sessions#new"
    get "sign_out", :to => "administrators/sessions#destroy"
  end

  get 'reserves/index'
  devise_for :oaccounts, :controllers =>{
    :registrations => 'oaccounts/registrations',
    :sessions => 'oaccounts/sessions'
  }
  devise_scope :oaccount do
    get "osign_in", :to => "oaccounts/sessions#new"
    get "osign_out", :to => "oaccounts/sessions#destroy"
  end
  namespace :oaccounts do
    resources :notices, only: [:index, :destroy]
  end

  devise_for :uaccounts, :controllers => {
    :registrations => 'uaccounts/registrations',
    :sessions => 'uaccounts/sessions'
  }
  devise_scope :uacoount do
    get "usign_in", :to => "uaccounts/sessions#new"
    get "usign_out", :to => "uaccounts/sessions#destroy"
  end

  namespace :uaccounts do
    resources :notices, only: [:index, :destroy]
  end
# usersメニュー　routing
  resources :users do
    member do
      post "confirm"
    end
  end
  # officesメニュー　routing
  resources :offices do
    member do
      post "confirm"
      post "find"
      get "bed_article"
      get "bed_article_edit"
      post "bed_article_confirm"
      post "bed_article_update"
    end
  end

  # reserves　メニューrouting
  resources :reserves do
    resources :comments, only: [:create, :destroy, :update]
    member do
      get "index"
      get "bed_show"
      get "reserve_show"
      get "comment_index"
      get "notice_index"
      post "delete_confirm"
      post "delete"
      post "edit"
      post "edit_confirm"
      post "edit_update"
    end
    collection do
      resources :favorites, only: [:create, :index] do
        collection do
          delete "destroy", as: :destroy
        end
      end
      get "service_date"
      get "permit_index"
      get "decline_index"
      get "history_index"
      get "favorite_index"
      get "info_type"
      post "confirm"
    end
  end
  resources :matters do
    member do
      post "edit_confirm"
      post "edit"
      post "destroy_confirm"
    end
    collection do
      post "confirm"
    end
  end
  resources :reserve_selves do
    resources :comments, only: [:create, :destroy, :update]
    member do
      get "decline_index"
      get "permit_index"
      get "history_index"
      get "comment_index"
      get "matter_index"
      get "matter_show"
      get "index"
      get "service_date"
      get "reserve_show"
      get "month_total"
      get "notice_index"
      post "permit_confirm"
      post "permit"
      post "decline_confirm"
      post "decline"
      post "decline_cancel_confirm"
      post "decline_cancel"
      post "cancel_confirm"
      post "cancel"
      post "edit"
      post "edit_confirm"
      post "edit_update"
    end
    collection do
      post "confirm"
    end
  end
  # mainメニュー　routing
  get "/", to:  "main#index", as: :root

  resources :main do
    member do
      get "show"
    end
    collection do
      get "index"
      get "info_type"
      get "contact"
      get "faq"
      get "privacy_policy"
      get "map"
      post "contact_confirm"
      post "send_contact"
    end
  end
  namespace :admin do
    resources :home, only: [:index] do

    end
    resources :prefectures do
      member do
        post "confirm_delete"
      end
    end
  end
  #adminメニュー
  resources :admin do
    member do
      post "confirm_delete_city"
      get "edit_city"
      post "update_city"
      post "delete_city"
      get "edit_office"
      post "confirm_office"
      post "update_office"
      post "delete_office_confirm"
      post "delete_office"
      get "edit_bedtype"
      post "update_bedtype"
      post "delete_bedtype"
      post "confirm_delete_bedtype"
      post "delete_uaccount_confirm"
      post "delete_uaccount"
      get "reserve_show"
    end
    collection do
      get "new_city"
      post "new_city_update"
      get "city_index"
      get "info_delete"
      get "new_bedtype"
      post "new_bedtype_update"
      get "bedtype_index"
      get "uaccount_index"
      get "mail_all_send"
      post "mail_all_send_confirm"
      post "all_uaccounts_send"
      get "reserves_index"
    end
  end
end

app/models/office.rb
class Office < ApplicationRecord
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController

  before_action :get_oaccount,only: [:bed_show, :bed_article, :edit, :confirm, :update]
  def index
    @oaccounts = Oaccount.all

  end

  def bed_article
    @oaccount=Oaccount.find(params[:id])

    @calendars = (1..(@oaccount.max_reservation_months)).map do |i|
      Date.today.beginning_of_month.next_month(i - 1)
    end.map do |d|
      end_of_month = d.end_of_month
      {
        month: d.month.month,
        beginning_of_month: d,
        end_of_month: end_of_month,
        reserve_statuses: @oaccount.reserve_statuses(d, end_of_month),
        beginning_of_calender: d.ago(d.wday.day).to_date,
        end_of_calender: end_of_month.since((6-end_of_month.wday).day)
      }
    end
  end

  def bed_article_edit
    bed_article
    @forms = ReserveCount.reserve_count_models([@calendars.first[:beginning_of_month], Date.today].max, @calendars.last[:end_of_month], @oaccount)
  end

  def bed_article_confirm
    bed_article_edit
    params_hash=update_disable_bed_count_params[:reserve_counts].to_h.map{|k, v|[Date.parse(v[:date]), v[:disable_bed_count].to_i]}.to_h
    @forms.each do |k, v|
      v.disable_bed_count=params_hash[k]
    end

  end

  def bed_article_update
    bed_article_confirm
    ActiveRecord::Base.transaction do
      @forms.values.each(&:save_disable_bed_count!)
    end
    redirect_to bed_article_office_path(current_oaccount.id)
  end

  def confirm
    @oaccount.assign_attributes(update_params)
    @oaccount.attachment_changes["thumbnail"]&.save
    @oaccount.attachment_changes["pdf_info"]&.save
  end

  def edit

  end

  def update
    @oaccount.update(update_params)
    flash[:notice] = "事業所情報が更新されました"
    redirect_to main_path(@oaccount.id)
  end

  def login_form

  end

  def create
  end

  def reserve_index
  end

  private
    def get_oaccount
      id=current_oaccount&.id || params[:id]
      @oaccount=Oaccount.eager_load(office_city: :prefecture).find(id)
    end
    def update_params
      params.require(:oaccount).permit(:office_num, :max_reservation_months, :medical_practice, :trance_area,
         :address, :startday, :thumbnail, :office_name, :email, :office_city_id, :office_phone, :office_url,
          :office_bed_count, :office_bed_type, :office_apear, :pdf_info, :fax_num, :bed_type2_id)
    end
    def update_disable_bed_count_params
      params.require(:reserve_counts).permit(reserve_counts: [:disable_bed_count, :date])
    end
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/views/offices/bed_article.html.erb
<div id="main">
  <article>
    <h2>詳細ページ</h2>

    <!-- <p class="c"><%= @oaccount.office_name%>の空き状況</p>  -->
    <h3><%= @oaccount.office_name%>の空き状況(詳細)</h3>

    <!-- <figure class="mb30"><img src="images/sample1.jpg" alt="ここにショートステイの絵を入れる"></figure> -->
    <table class="ta1">
      <caption>詳細情報</caption>
      <tr>
      <th>ベッド数</th>
      <td><%= @oaccount.office_bed_count %>床</td>
      </tr>
      <tr>
      <th>部屋の種類</th>
      <td>個室</td>
      </tr>
    </table>
    <% @calendars.each do |calendar| %>
      <%= month_calendar(start_date: calendar[:beginning_of_month]) do |date| %>
      <%= date.strftime("%m/%d") %><br>
        <% if Date.today > date %>
          <%= "-" %>
        <% else %>
          <%= link_to(calendar[:reserve_statuses][date][:count],new_reserve_self_path(date: date.strftime("%Y-%m-%d"))) %>
          <br>
          <%= link_to("利用一覧", permit_index_reserve_self_path(reserve_search_condition: {date: date.strftime("%Y-%m-%d")})) %>
        <% end %>
      <% end %>
      <br>
    <% end %>
  </article>
</div>
<!--/#main -->

app/views/offices/bed_article_confirm.html.erb
<div id="main">
  <article>
    <h2>詳細ページ</h2>

    <!-- <p class="c"><%= @oaccount.office_name%>の空き状況</p>  -->
    <h3><%= @oaccount.office_name%>の空き状況(詳細)</h3>

    <!-- <figure class="mb30"><img src="images/sample1.jpg" alt="ここにショートステイの絵を入れる"></figure> -->
    <table class="ta1">
      <caption>詳細情報</caption>
      <tr>
      <th>ベッド数</th>
      <td><%= @oaccount.office_bed_count %>床</td>
      </tr>
      <tr>
      <th>部屋の種類</th>
      <td>個室</td>
      </tr>
    </table>

    <%= form_with(model: @forms, url: bed_article_update_office_path, scope: :reserve_counts) do |reserve_count_form| %>
      <% @calendars.each do |calendar| %>
        <%= month_calendar(start_date: calendar[:beginning_of_month]) do |date| %>
          <%= date.strftime("%m/%d") %><br>
          <% if Date.today > date %>
            <%= "-" %>
          <% else %>
            <%= link_to(calendar[:reserve_statuses][date][:count], new_reserve_self_path(date: date.strftime("%Y-%m-%d"))) %>
            <br>
            <%= link_to("利用一覧", permit_index_reserve_self_path(reserve_search_condition: {date: date.strftime("%Y-%m-%d")})) %>
            <br>
            <%= reserve_count_form.fields_for("reserve_counts", reserve_count_form.object[date], index: @forms.values.index(reserve_count_form.object[date])) do |f| %>
              <%= f.hidden_field :date %>
              <%= f.hidden_field :disable_bed_count %>
              <%= f.object.disable_bed_count %>
            <% end %>
          <% end %>
        <% end %>
        <%= reserve_count_form.submit "変更を登録する" %>
        <br>
      <% end %>
    <% end %>

  </article>
</div>
<!--/#main -->

app/views/offices/bed_article_edit.html.erb
<div id="main">
  <article>
    <h2>詳細ページ</h2>

    <!-- <p class="c"><%= @oaccount.office_name%>の空き状況</p>  -->
    <h3><%= @oaccount.office_name%>の空き状況(詳細)</h3>

    <!-- <figure class="mb30"><img src="images/sample1.jpg" alt="ここにショートステイの絵を入れる"></figure> -->
    <table class="ta1">
      <caption>詳細情報</caption>
      <tr>
      <th>ベッド数</th>
      <td><%= @oaccount.office_bed_count %>床</td>
      </tr>
      <tr>
      <th>部屋の種類</th>
      <td>個室</td>
      </tr>
    </table>
    すでに利用が決まっているベッド数を入力してください
    <%= form_with(model: @forms, url: bed_article_confirm_office_path, scope: :reserve_counts) do |reserve_count_form| %>
      <% @calendars.each do |calendar| %>
        <%= month_calendar(start_date: calendar[:beginning_of_month]) do |date| %>
          <%= date.strftime("%m/%d") %><br>
          <% if Date.today > date %>
            <%= "-" %>
          <% else %>
            <%= link_to(calendar[:reserve_statuses][date][:count], new_reserve_self_path(date: date.strftime("%Y-%m-%d"))) %>
            <br>
            <%= link_to("利用一覧", permit_index_reserve_self_path(reserve_search_condition: {date: date.strftime("%Y-%m-%d")})) %>
            <br>
            <%= reserve_count_form.fields_for("reserve_counts", reserve_count_form.object[date], index: @forms.values.index(reserve_count_form.object[date])) do |f| %>
              <%= f.hidden_field :date %>
              <%= f.text_field :disable_bed_count, size: "3" %>
            <% end %>
          <% end %>
        <% end %>
        <%= reserve_count_form.submit "確認画面へ" %>
        <br>
      <% end %>
    <% end %>
  </article>
</div>
<!--/#main -->

app/views/offices/confirm.html.erb
<div id="main">

	<section>

		<%= form_with(model: @oaccount, url: office_path, method: :patch) do |f| %>
			<table class="ta1">
				<tr>
					<th>事業所名</th>
					<td><%= f.hidden_field :office_name %><%= @oaccount.office_name %></td>
				</tr>
				<tr>
					<th>事業所番号</th>
					<td><%= f.hidden_field :office_num %><%= @oaccount.office_num %></td>
				</tr>
				<tr>
					<th>地区</th>
					<td><%= f.hidden_field :office_city_id %><%= @oaccount.office_city_id %>　<% @city=City.find(@oaccount.office_city_id) %><%= @city.city_name %></td>
				</tr>
				<tr>
					<th>住所</th>
					<td><%= f.hidden_field :address %><%= @oaccount.address %></td>
				</tr>
				<tr>
					<th>電話番号</th>
					<td><%= f.hidden_field :office_phone %><%= @oaccount.office_phone %></td>
				</tr>
				<tr>
					<th>FAX番号</th>
					<td><%= f.hidden_field :fax_num %><%= @oaccount.fax_num %></td>
				</tr>
				<tr>
					<th>ベッド数</th>
					<td><%= f.hidden_field :office_bed_count %><%= @oaccount.office_bed_count %></td>
				</tr>
				<tr>
					<th>ベッド種類1</th>
					<td><%= f.hidden_field :office_bed_type %><%= @oaccount.bed_type&.bed_type %></td>
				</tr>
				<tr>
					<th>ベッド種類2</th>
					<td><%= f.hidden_field :bed_type2_id %><%= @oaccount.bed_type2&.bed_type %></td>
				</tr>
				<tr>
					<th>送迎範囲</th>
					<td><%= f.hidden_field :trance_area %><%= @oaccount.trance_area %></td>
				</tr>
				<tr>
					<th>医療行為について</th>
					<td><%= f.hidden_field :medical_practice %><%= @oaccount.medical_practice %></td>
				</tr>
				<tr>
					<th>ホームページ</th>
					<td><%= f.hidden_field :office_url %><%= @oaccount.office_url %></td>
				</tr>
				<tr>
					<th>施設のアピールポイント</th>
					<td><%= f.hidden_field :office_apear %><%= safe_join(@oaccount.office_apear.split("\n"),tag(:br)) %></td>
				</tr>
				<tr>
					<th>ベッド管理開始日</th>
					<td><%= f.hidden_field :startday %><%= @oaccount.startday %></td>
				</tr>
				<tr>
					<th>画像サムネイル</th>
					<td>
						<% if f.object.thumbnail.attached? %>
							<%= f.hidden_field :thumbnail, value: f.object.thumbnail.signed_id %>
							<%= image_tag f.object.thumbnail %>
						<% end %>
					</td>
				</tr>
				<tr>
					<th>申し込み</th>
					<td>
						<% if f.object.pdf_info.attached? %>
							<%= f.hidden_field :pdf_info, value: f.object.pdf_info.signed_id %>
							<iframe src="<%= url_for(@oaccount.pdf_info) %>">
							</iframe>

						<% end %>
					</td>
				</tr>
				<tr>
					<th>表示・予約の限界月数</th>
					<td><%= f.hidden_field :max_reservation_months %><%= @oaccount.max_reservation_months %></td>
				</tr>
			</table>

			<p class="c">
				<%= f.submit "内容を保存する", class: "btn", disable_with: '保存中' %>
			</p>
		<% end %>
	</section>

</div>
<!--/#main-->

app/views/offices/edit.html.erb
<div id="main">

	<section>

		<%= form_with(model: @oaccount, url: confirm_office_path, method: :post) do |f| %>
			<table class="ta1">
				<tr>
					<th>事業所名</th>
					<td><%= f.text_field :office_name, size:30, class:"ws" %></td>
				</tr>
				<tr>
					<th>事業所番号</th>
					<td><%= f.text_field :office_num, size:30, class:"ws" %></td>
				</tr>
				<tr>
					<th>地区</th>
					<td><%= f.collection_select :office_city_id, City.eager_load(:prefecture).all, :id, :full_name, {include_blank: true}, class:"ws js-select2" %></td>
				</tr>
				<tr>
					<th>住所</th>
					<td><%= f.text_field :address, size:30, class:"ws" %></td>
				</tr>
				<tr>
					<th>電話番号</th>
					<td><%= f.text_field :office_phone, size:10, class:"ws" %></td>
				</tr>
				<tr>
					<th>FAX番号</th>
					<td><%= f.text_field :fax_num, size:10, class:"ws" %></td>
				</tr>
				<tr>
					<th>ベッド数</th>
					<td><%= f.number_field :office_bed_count, size:3 %></td>
				</tr>
				<tr>
					<th>ベッド種類1</th>
					<td><%= f.collection_select :office_bed_type, Bedtype.all, :id, :bed_type, size:10, class:"ws" %></td>
				</tr>
				<tr>
					<th>ベッド種類2</th>
					<td><%= f.collection_select :bed_type2_id, Bedtype.all, :id, :bed_type, size:10, class:"ws" %></td>
				</tr>
				<tr>
					<th>送迎範囲</th>
					<td><%= f.text_field :trance_area, size:30 %></td>
				</tr>
				<tr>
					<th>医療行為について</th>
					<td><%= f.text_field :medical_practice, size:30 %></td>
				</tr>
				<tr>
					<th>施設のアピールポイント</th>
					<td><%= f.text_area :office_apear, class: 'wl', size: "20x10"  %></td>
				</tr>
				<tr>
					<th>ベッド管理開始日</th>
					<td><%= f.date_field :startday, size:10 %></td>
				</tr>
				<tr>
					<th>ホームページ</th>
					<td><%= f.text_field :office_url, size:30, class:"ws" %></td>
				</tr>
				<tr>
					<th>サムネイル画像</th>
					<td><%= f.file_field :thumbnail %></td>
				</tr>
				<tr>
					<th>申し込み用紙</th>
					<td><%= f.file_field :pdf_info %></td>
				</tr>
				<tr>
					<th>表示・予約の限界月数</th>
					<td>予約ができる限界の月数です。3と入れれば3ヶ月先までしか予約を入れることができません<br>
							<%= f.number_field :max_reservation_months %></td>
				</tr>

			</table>

			<p class="c">
				<%= f.submit "内容を確認する", class:"btn" %>
			</p>
		<% end %>
	</section>

</div>
<!--/#main-->