config/routes.rb
Rails.application.routes.draw do
  devise_for :administrators, :controllers =>{
    :registrations => 'administrators/registrations',
    :sessions => 'administrators/sessions'
  }
  devise_scope :administrator do
    get "sign_in", :to => "administrators/sessions#new"
    get "sign_out", :to => "administrators/sessions#destroy"
  end

  get 'reserves/index'
  devise_for :oaccounts, :controllers =>{
    :registrations => 'oaccounts/registrations',
    :sessions => 'oaccounts/sessions'
  }
  devise_scope :oaccount do
    get "osign_in", :to => "oaccounts/sessions#new"
    get "osign_out", :to => "oaccounts/sessions#destroy"
  end
  namespace :oaccounts do
    resources :notices, only: [:index, :destroy]
  end

  devise_for :uaccounts, :controllers => {
    :registrations => 'uaccounts/registrations',
    :sessions => 'uaccounts/sessions'
  }
  devise_scope :uacoount do
    get "usign_in", :to => "uaccounts/sessions#new"
    get "usign_out", :to => "uaccounts/sessions#destroy"
  end

  namespace :uaccounts do
    resources :notices, only: [:index, :destroy]
  end
# usersメニュー　routing
  resources :users do
    member do
      post "confirm"
    end
  end
  # officesメニュー　routing
  resources :offices do
    member do
      post "confirm"
      post "find"
      get "bed_article"
      get "bed_article_edit"
      post "bed_article_confirm"
      post "bed_article_update"
    end
  end

  # reserves　メニューrouting
  resources :reserves do
    resources :comments, only: [:create, :destroy, :update]
    member do
      get "index"
      get "bed_show"
      get "reserve_show"
      get "comment_index"
      get "notice_index"
      post "delete_confirm"
      post "delete"
      post "edit"
      post "edit_confirm"
      post "edit_update"
    end
    collection do
      resources :favorites, only: [:create, :index] do
        collection do
          delete "destroy", as: :destroy
        end
      end
      get "service_date"
      get "permit_index"
      get "decline_index"
      get "history_index"
      get "favorite_index"
      get "info_type"
      post "confirm"
    end
  end
  resources :matters do
    member do
      post "edit_confirm"
      post "edit"
      post "destroy_confirm"
    end
    collection do
      post "confirm"
    end
  end
  resources :reserve_selves do
    resources :comments, only: [:create, :destroy, :update]
    member do
      get "decline_index"
      get "permit_index"
      get "history_index"
      get "comment_index"
      get "matter_index"
      get "matter_show"
      get "index"
      get "service_date"
      get "reserve_show"
      get "month_total"
      get "notice_index"
      post "permit_confirm"
      post "permit"
      post "decline_confirm"
      post "decline"
      post "decline_cancel_confirm"
      post "decline_cancel"
      post "cancel_confirm"
      post "cancel"
      post "edit"
      post "edit_confirm"
      post "edit_update"
    end
    collection do
      post "confirm"
    end
  end
  # mainメニュー　routing
  get "/", to:  "main#index", as: :root

  resources :main do
    member do
      get "show"
    end
    collection do
      get "index"
      get "info_type"
      get "contact"
      get "faq"
      get "privacy_policy"
      get "map"
      post "contact_confirm"
      post "send_contact"
    end
  end
  namespace :admin do
    resources :home, only: [:index] do

    end
    resources :prefectures do
      member do
        post "confirm_delete"
      end
    end
  end
  #adminメニュー
  resources :admin do
    member do
      post "confirm_delete_city"
      get "edit_city"
      post "update_city"
      post "delete_city"
      get "edit_office"
      post "confirm_office"
      post "update_office"
      post "delete_office_confirm"
      post "delete_office"
      get "edit_bedtype"
      post "update_bedtype"
      post "delete_bedtype"
      post "confirm_delete_bedtype"
      post "delete_uaccount_confirm"
      post "delete_uaccount"
      get "reserve_show"
    end
    collection do
      get "new_city"
      post "new_city_update"
      get "city_index"
      get "info_delete"
      get "new_bedtype"
      post "new_bedtype_update"
      get "bedtype_index"
      get "uaccount_index"
      get "mail_all_send"
      post "mail_all_send_confirm"
      post "all_uaccounts_send"
      get "reserves_index"
    end
  end
end

app/views/admin/bedtype_index.html.erb
<div id="main">
  <p><%= link_to("管理画面TOPに戻る", admin_home_index_path ) %></p>

  <section>

    <h2>ベッドの種類　一覧表</h2>

    <% @bedtypes.each do |bedtype| %>
      <div class="list link">
        <h4><%= bedtype.id %>　<%= bedtype.bed_type %></h4>
        <p><%= link_to("ベッドの種類を変更する", edit_bedtype_admin_path(bedtype.id)) %></p>
        <p><%= button_to("ベッドの種類を削除する", delete_bedtype_admin_path(bedtype.id), method: :post, class: "button-v2") %></p>
      </div>
    <% end %>

  </section>

</div>
<!--/#main-->

app/views/admin/confirm_delete_bedtype_admin.html.erb
<div id="main">
  <p><%= link_to("管理画面TOPに戻る", admin_home_index_path ) %></p>

	<section>
		<%= form_with(model: @bedtype, url: delete_bedtype_admin_path, method: :POST) do |f| %>
			<table class="ta1">
				<tr>
					<th>ベッドの種類</th>
					<td><%= f.hidden_field :bed_type %><%= @bedtype.bedtype %></td>
				</tr>
			</table>
			<p class="c">
				<%= "これを削除すると元に戻せません。また消すことにより画面が表示されなくなることがあります。" %>
				<%= f.submit "ベッドの種類を削除する", class:"btn" %>
			</p>
		<% end %>
	</section>

</div>

app/views/admin/confirm_delete_city.html.erb
<div id="main">
  <p><%= link_to("管理画面TOPに戻る", admin_home_index_path ) %></p>

	<section>
		<%= form_with(model: @city, url: delete_city_admin_path, method: :POST) do |f| %>
			<table class="ta1">
				<tr>
					<th>地区</th>
					<td><%= f.hidden_field :city_name %><%= @city.city_name  %></td>
				</tr>
				<tr>
					<th>関連する都道府県</th>
					<td><%= f.hidden_field :prefecture_id %><%= @city.prefecture.prefecture %></td>
				</tr>
			</table>
			<p class="c">
				<%= f.submit "この地区を削除する", class:"btn" %>
			</p>
		<% end %>
	</section>

</div>

app/views/admin/confirm_office.html.erb
<div id="main">

	<section>
 		<p><%= link_to("管理画面TOPに戻る", admin_home_index_path ) %></p>

		<%= form_with(model: @oaccount, url: update_office_admin_path, method: :post) do |f| %>
			<table class="ta1">
				<tr>
					<th>事業所名</th>
					<td><%= f.hidden_field :office_name %><%= @oaccount.office_name %></td>
				</tr>
				<tr>
					<th>事業所番号</th>
					<td><%= f.hidden_field :office_num %><%= @oaccount.office_num %></td>
				</tr>
				<tr>
					<th>e-mail</th>
					<td><%= f.hidden_field :email %><%= @oaccount.email %></td>
				</tr>
				<tr>
					<th>地区</th>
					<td><%= f.hidden_field :office_city_id %><%= @oaccount.office_city_id %>　<%= @oaccount.office_city.city_name %></td>
				</tr>
				<tr>
					<th>住所</th>
					<td><%= f.hidden_field :address %><%= @oaccount.address %></td>
				</tr>
				<tr>
					<th>電話番号</th>
					<td><%= f.hidden_field :office_phone %><%= @oaccount.office_phone %></td>
				</tr>
				<tr>
					<th>FAX番号</th>
					<td><%= f.hidden_field :fax_num %><%= @oaccount.fax_num %></td>
				</tr>
				<tr>
					<th>ベッド数</th>
					<td><%= f.hidden_field :office_bed_count %><%= @oaccount.office_bed_count %></td>
				</tr>
				<tr>
					<th>ベッド種類1</th>
					<td><%= f.hidden_field :office_bed_type %><%= @oaccount.office_bed_type %>　<%= @oaccount.bed_type&.bed_type %></td>
				</tr>
				<tr>
					<th>ベッド種類2</th>
					<td><%= f.hidden_field :bed_type2_id %><%= @oaccount.bed_type2_id %>　<%= @oaccount.bed_type2&.bed_type %></td>
				</tr>
				<tr>
					<th>送迎範囲</th>
					<td><%= f.hidden_field :trance_area %><%= @oaccount.trance_area %></td>
				</tr>
				<tr>
					<th>医療行為について</th>
					<td><%= f.hidden_field :medical_practice %><%= @oaccount.medical_practice %></td>
				</tr>
				<tr>
					<th>施設のアピールポイント</th>
					<td><%= f.hidden_field :office_apear %><%= @oaccount.office_apear %></td>
				</tr>
				<tr>
					<th>ベッド管理開始日</th>
					<td><%= f.hidden_field :startday %><%= @oaccount.startday %></td>
				</tr>
				<tr>
					<th>ホームページ</th>
					<td><%= f.hidden_field :office_url %><%= @oaccount.office_url %></td>
				</tr>
				<tr>
					<th>画像サムネイル</th>
					<td>
						<% if f.object.thumbnail.attached? %>
							<%= f.hidden_field :thumbnail, value: f.object.thumbnail.signed_id %>
							<%= image_tag f.object.thumbnail %>
						<% end %>
					</td>
				</tr>
				<tr>
					<th>表示sw</th>
					<td><%= f.hidden_field :display_sw %><%= @oaccount.display_sw %></td>
				</tr>
				<tr>
					<th>表示順ポイント</th>
					<td><%= f.hidden_field :display_sort %><%= @oaccount.display_sort %></td>
				</tr>
				<tr>
					<th>表示・予約の限界月数</th>
					<td><%= f.hidden_field :max_reservation_months %><%= @oaccount.max_reservation_months %></td>
				</tr>
				<tr>
					<th>有料　事業所</th>
					<td><%= f.hidden_field :paid_oaccount %><%= @oaccount.paid_oaccount %></td>
				</tr>
			</table>

			<p class="c">
				<%= f.submit "内容を保存する", class: "btn", disable_with: '保存中' %>
			</p>
		<% end %>
	</section>

</div>
<!--/#main-->

app/views/admin/delete_uaccount_confirm.html.erb
<div id="main">

<section>
  <p><%= link_to("管理画面TOPに戻る", admin_home_index_path ) %></p>

	<%= form_with(model: @uaccount, url: delete_uaccount_admin_path, method: :post) do |f| %>
		<table class="ta1">
			<tr>
				<th>お名前</th>
				<td><%= f.hidden_field :user_name %><%= @uaccount.user_name %></td>
			</tr>
			<tr>
				<th>メールアドレス</th>
				<td><%= f.hidden_field :email %><%= @uaccount.email %></td>
			</tr>
			<tr>
				<th>事業所名</th>
				<td><%= f.hidden_field :user_office%><%= @uaccount.user_office %></td>
			</tr>
			<tr>
				<th>電話番号</th>
				<td><%= f.hidden_field :user_phone %><%= @uaccount.user_phone %></td>
			</tr>
		</table>
		データを削除すると、このデータに関連した予約が表示されなくなり、エラーになる場合があります。
		本当に消してもよろしいですか？
		<p class="c">
			<input type="submit" value="このケアマネを削除" class="btn">
		</p>
	<% end %>

</section>

</div>
<!--/#main-->

app/views/admin/edit_bedtype.html.erb
<div id="main">
  <p><%= link_to("管理画面TOPに戻る", admin_home_index_path ) %></p>

	<section>
		<%= form_with(model: @bedtype, url: update_bedtype_admin_path, method: :POST) do |f| %>
			<table class="ta1">
				<tr>
					<th>ベッドの種類</th>
					<td><%= f.text_area :bed_type, size: "10", class:"wl" %></td>
				</tr>
			</table>
			<p class="c">
				<%= f.submit "編集内容を保存する", class:"btn" %>
			</p>
		<% end %>
	</section>

</div>

app/views/admin/edit_city.html.erb
<div id="main">
  <p><%= link_to("管理画面TOPに戻る", admin_home_index_path ) %></p>

	<section>
		<%= form_with(model: @city, url: update_city_admin_path, method: :POST) do |f| %>
			<table class="ta1">
				<tr>
					<th>地区</th>
					<td><%= f.text_area :city_name, size: "5", class:"wl" %></td>
				</tr>
				<tr>
					<th>関連する都道府県</th>
					<td><%= f.collection_select :prefecture_id, Prefecture.all, :id, :prefecture, size:30, class:"ws" %></td>
				</tr>
			</table>
			<p class="c">
				<%= f.submit "編集内容を確認する", class:"btn" %>
			</p>
		<% end %>
	</section>

</div>

app/views/admin/edit_office.html.erb
<div id="main">

	<section>
	  <p><%= link_to("管理画面TOPに戻る", admin_home_index_path ) %></p>

		<%= form_with(model: @oaccount, url: confirm_office_admin_path, method: :post) do |f| %>
			<table class="ta1">
				<tr>
					<th>事業所名</th>
					<td><%= f.text_field :office_name, size:30, class:"ws" %></td>
				</tr>
				<tr>
					<th>事業所番号</th>
					<td><%= f.text_field :office_num, size:30, class:"ws" %></td>
				</tr>
				<tr>
					<th>e-mail</th>
					<td><%= f.text_field :email, size:30, class:"ws" %></td>
				</tr>
				<tr>
					<th>地区</th>
					<td><%= f.collection_select :office_city_id, City.eager_load(:prefecture).all, :id, :full_name, include_blank: true, size:10, class:"ws js-select2" %></td>
				</tr>
				<tr>
					<th>住所</th>
					<td><%= f.text_field :address, size:30, class:"ws" %></td>
				</tr>
				<tr>
					<th>電話番号</th>
					<td><%= f.text_field :office_phone, size:10, class:"ws" %></td>
				</tr>
				<tr>
					<th>FAX番号</th>
					<td><%= f.text_field :fax_num, size:10, class:"ws" %></td>
				</tr>
				<tr>
					<th>ベッド数</th>
					<td><%= f.number_field :office_bed_count, size:10, class:"ws" %></td>
				</tr>
				<tr>
					<th>ベッド種類1</th>
					<td><%= f.collection_select :office_bed_type, Bedtype.all, :id, :bed_type, {include_blank: true}  %></td>
				</tr>
				<tr>
					<th>ベッド種類2</th>
					<td><%= f.collection_select :bed_type2_id, Bedtype.all, :id, :bed_type, {include_blank: true}  %></td>
				</tr>
				<tr>
					<th>送迎範囲</th>
					<td><%= f.text_field :trance_area, size:30 %></td>
				</tr>
				<tr>
					<th>医療行為について</th>
					<td><%= f.text_field :medical_practice, size:30 %></td>
				</tr>
				<tr>
					<th>施設のアピールポイント</th>
					<td><%= f.text_area :office_apear, class:"wl", size: "20x10" %></td>
				</tr>
				<tr>
					<th>ベッド管理開始日</th>
					<td><%= f.date_field :startday, size:10 %></td>
				</tr>
				<tr>
					<th>ホームページ</th>
					<td><%= f.text_field :office_url, size:30, class:"ws" %></td>
				</tr>
				<tr>
					<th>サムネイル画像</th>
					<td><%= f.file_field :thumbnail %></td>
				</tr>
				<tr>
					<th>表示スイッチ</th>
					<td>
							<%= f.check_box :display_sw, {}, "display_status", "no_display_status" %>
							<%= f.label :display_sw, "この事業所をリストに表示する（チェックを外すと全てのリストに表示されなくなります）" %>
					</td>
				</tr>
				<tr>
					<th>表示順ポイント</th>
					<td>数字が大きいほど上位に表示されます<br>
							<%= f.number_field :display_sort, size:10, class:"ws" %></td>
				</tr>
				<tr>
					<th>表示・予約の限界月数</th>
					<td>予約ができる限界の月数です。3と入れれば3ヶ月先までしか予約を入れることができません<br>
							<%= f.number_field :max_reservation_months, size:10, class:"ws" %></td>
				</tr>
				<tr>
					<th>有料ユーザー</th>
					<td>
							<%= f.check_box :paid_oaccount, {}, "paid_oaccount", "no_paid_oaccount" %>
							<%= f.label :paid_oaccount, "有料　事業所（チェックを付けたらケアマネからの予約を受け付けることができます）" %>
					</td>
				</tr>
			</table>

			<p class="c">
				<%= f.submit "内容を確認する", class:"btn" %>
			</p>
		<% end %>
	</section>

</div>
<!--/#main-->

app/views/admin/new_bedtype.html.erb
<div id="main">
  <p><%= link_to("管理画面TOPに戻る", admin_home_index_path ) %></p>

	<section>
		<%= form_with(model: @bedtype, url: new_bedtype_update_admin_index_path, method: :POST) do |f| %>
			<table class="ta1">
				<tr>
					<th>ベッドの種類</th>
					<td><%= f.text_area :bed_type, size: "10", class:"wl" %></td>
				</tr>
			</table>
			<p class="c">
				<%= f.submit "ベッドの種類を新規登録する", class:"btn" %>
			</p>
		<% end %>
	</section>

</div>

app/views/admin/new_city.html.erb
<div id="main">
  <p><%= link_to("管理画面TOPに戻る", admin_home_index_path ) %></p>

	<section>
		<%= form_with(model: @city, url: new_city_update_admin_index_path, method: :POST) do |f| %>
			<table class="ta1">
				<tr>
					<th>地区</th>
					<td><%= f.text_area :city_name, size: "5", class:"wl" %></td>
				</tr>
				<tr>
					<th>関連する都道府県</th>
					<td><%= f.collection_select :prefecture_id, Prefecture.all, :id, :prefecture, size:30, class:"ws" %></td>
				</tr>
			</table>
			<p class="c">
				<%= f.submit "地区を追加する", class:"btn" %>
			</p>
		<% end %>
	</section>

</div>

app/views/admin/reserve_log_index.html.erb
<div id="main">

  <section>
    <p><%= link_to("管理画面TOPに戻る", admin_home_index_path ) %></p>

    <h2>過去３カ月の予約リストです</h2>
    <p>退園日順になっています。</p>

    <% @reserves.each do |reserve| %>
      <div class="list link">
        <div class="listinboxA">
          <div class="listinbox2">
            <h4><% reserve&.office_id %><%= reserve.oaccount&.office_name %></h4>
            <p><i class="zmdi zmdi-account"></i>　<%= "#{reserve.client_name}様" if reserve.client_name.present? %></p>
            <p><%= link_to("予約期間#{reserve.start_date}〜#{reserve.end_date}", reserve_show_reserf_path(reserve.id)) %></p>
            <p>備考：<%= reserve.remark %></p>
          </div>
          <div class="listinboxr3">
            <br>
            <p>予約状況：<%= reserve.entry_flg %></p>
            <p><i class="zmdi zmdi-phone"></i> <%= reserve.oaccount.office_phone %>
            <p><i class="zmdi zmdi-car">迎え</i> <%= reserve.start_transfer.trans_flg %></p>
            <p><i class="zmdi zmdi-car">送り</i> <%= reserve.end_transfer.trans_flg %></p>
          </div>

        </div>
      </div>
    <% end %>
  <%= paginate @reserves %>
  </section>

</div>
<!--/#main-->

app/views/admin/reserve_show.html.erb
<div id="main">

	<section>
	  <p><%= link_to("管理画面TOPに戻る", admin_home_index_path ) %></p>

			<table class="ta1">
			  <div class="button-modoru-box">
        	<%= link_to "戻る", 'javascript:history.back()', method: :get, class: "button-modoru" %>
        </div>
				<tr>
					<th>ケアマネジャー</th>
					<td><%= @reserve.uaccount&.user_name %></td>
				</tr>
				<tr>
					<th>ショートステイ事業所番号</th>
					<td><%= @reserve.oaccount.office_name %></td>
				</tr>
				<tr>
					<th>利用者名</th>
					<td><%= @reserve.user_name || @reserve.client_name %></td>
				</tr>
				<tr>
					<th>開始日</th>
					<td><%= @reserve.start_date.strftime("%Y年%m月%d日") %></td>
				</tr>
				<tr>
					<th>迎えの送迎</th>
					<td><%= @reserve.start_transfer.trans_flg %></td>
				</tr>
				<tr>
					<th>終了日</th>
					<td><%= @reserve.end_date.strftime("%Y年%m月%d日") %></td>
				</tr>

				<tr>
					<th>送りの送迎</th>
					<td><%= @reserve.end_transfer.trans_flg %></td>
				</tr>
				<tr>
					<th>過去に利用がありますか？</th>
					<td><%= @reserve.past_use.past_use %></td>
				</tr>
				<tr>
					<th>備考欄</th>
					<td><%= @reserve.remark %></td>
				</tr>
			</table>
			<h2>ショートステイ連絡ボード</h2>
			<% @comments.each do |comment| %>
				<% if comment.sender_flg == "uaccount_comment" then %>
					<div class=comment_box_blue>
						<%= @reserve.uaccount.user_name %><br>
						<%= comment.comment %><br>
						送信日：<%= comment.created_at.strftime("%Y年%m月%d日(#{%w(日 月 火 水 木 金 土)[comment.created_at.wday]}曜日) %H:%M") %>
						<div class="button-choise-end"><%= button_to("削除", reserf_comment_path(id: comment.id, reserf_id: @reserve.id), method: :delete) %></div>
					</div>
				<% else %>
					<div class=comment_box_orange>
						<%= @reserve.oaccount.office_name %><br>
						<%= comment.comment %><br>
						送信日：<%= comment.created_at.strftime("%Y年%m月%d日(#{%w(日 月 火 水 木 金 土)[comment.created_at.wday]}曜日) %H:%M") %>
					</div>
				<% end %>
			<% end %>

	</section>

</div>
<!--/#main-->

app/views/admin/reserves_index.html.erb
<div id="main">

  <section>
    <p><%= link_to("管理画面TOPに戻る", admin_home_index_path ) %></p>

		<div class="button-modoru-box">
      <%= link_to "戻る", 'javascript:history.back()', method: :get, class: "button-modoru" %>
    </div>

    <h2>予約状況一覧表</h2>

    <% @reserves.each do |reserve| %>
      <div class="list link">
        <div class="listinboxA">
          <div class="listinboxr2">
            <h4>№<%= reserve.id %>  <%= reserve.display_user_name %></h4>
            <p><i class="zmdi zmdi-account"></i>　<%= "#{reserve.client_name}様" if reserve.client_name.present? %></p>
            <p><%= link_to("予約期間#{reserve.start_date.strftime("%Y/%m/%d")}〜#{reserve.end_date.strftime("%Y/%m/%d")}", reserve_show_admin_path(reserve.id)) %>
            <p>備考 <%= reserve.remark %></p>
          </div>
          <div class="listinboxr3">
            <i class="zmdi zmdi-city"></i> <%= reserve.display_user_office %><br>
            <i class="zmdi zmdi-phone"></i> <%= reserve.display_user_phone %><br>
            予約日： <%= reserve.created_at.strftime("%Y/%m/%d") %>
          </div>
        </div>
      </div>
    <% end %>
    <%= paginate @reserves %>
  </section>

</div>
<!--/#main-->

app/views/admin/uaccount_index.html.erb
<div id="main">

  <section>

    <h2>ケアマネジャー　一覧表</h2>

    <% @uaccounts.each do |uaccount| %>
      <div class="list link">
        <h4><%= uaccount.id %>　<%= uaccount.user_name %></h4>
        <p>メール確認日:<%= uaccount.confirmed_at&.strftime("%Y年%m月%d日(#{%w(日 月 火 水 木 金 土)[uaccount.confirmed_at.wday]}曜日) %H:%M") %></p>
        <p>居宅介護支援事業所：<%= uaccount.user_office  %>　<%= uaccount.email %></p>
        <p><%= button_to("ケアマネを削除する", delete_uaccount_confirm_admin_path(uaccount.id), method: :post, class: "button-v2") %></p>
      </div>
    <% end %>

  </section>

</div>
<!--/#main-->