config/routes.rb
Rails.application.routes.draw do
  devise_for :administrators, :controllers =>{
    :registrations => 'administrators/registrations',
    :sessions => 'administrators/sessions'
  }
  devise_scope :administrator do
    get "sign_in", :to => "administrators/sessions#new"
    get "sign_out", :to => "administrators/sessions#destroy"
  end

  get 'reserves/index'
  devise_for :oaccounts, :controllers =>{
    :registrations => 'oaccounts/registrations',
    :sessions => 'oaccounts/sessions'
  }
  devise_scope :oaccount do
    get "osign_in", :to => "oaccounts/sessions#new"
    get "osign_out", :to => "oaccounts/sessions#destroy"
  end
  namespace :oaccounts do
    resources :notices, only: [:index, :destroy]
  end

  devise_for :uaccounts, :controllers => {
    :registrations => 'uaccounts/registrations',
    :sessions => 'uaccounts/sessions'
  }
  devise_scope :uacoount do
    get "usign_in", :to => "uaccounts/sessions#new"
    get "usign_out", :to => "uaccounts/sessions#destroy"
  end

  namespace :uaccounts do
    resources :notices, only: [:index, :destroy]
  end
# usersメニュー　routing
  resources :users do
    member do
      post "confirm"
    end
  end
  # officesメニュー　routing
  resources :offices do
    member do
      post "confirm"
      post "find"
      get "bed_article"
      get "bed_article_edit"
      post "bed_article_confirm"
      post "bed_article_update"
    end
  end

  # reserves　メニューrouting
  resources :reserves do
    resources :comments, only: [:create, :destroy, :update]
    member do
      get "index"
      get "bed_show"
      get "reserve_show"
      get "comment_index"
      get "notice_index"
      post "delete_confirm"
      post "delete"
      post "edit"
      post "edit_confirm"
      post "edit_update"
    end
    collection do
      resources :favorites, only: [:create, :index] do
        collection do
          delete "destroy", as: :destroy
        end
      end
      get "service_date"
      get "permit_index"
      get "decline_index"
      get "history_index"
      get "favorite_index"
      get "info_type"
      post "confirm"
    end
  end
  resources :matters do
    member do
      post "edit_confirm"
      post "edit"
      post "destroy_confirm"
    end
    collection do
      post "confirm"
    end
  end
  resources :reserve_selves do
    resources :comments, only: [:create, :destroy, :update]
    member do
      get "decline_index"
      get "permit_index"
      get "history_index"
      get "comment_index"
      get "matter_index"
      get "matter_show"
      get "index"
      get "service_date"
      get "reserve_show"
      get "month_total"
      get "notice_index"
      post "permit_confirm"
      post "permit"
      post "decline_confirm"
      post "decline"
      post "decline_cancel_confirm"
      post "decline_cancel"
      post "cancel_confirm"
      post "cancel"
      post "edit"
      post "edit_confirm"
      post "edit_update"
    end
    collection do
      post "confirm"
    end
  end
  # mainメニュー　routing
  get "/", to:  "main#index", as: :root

  resources :main do
    member do
      get "show"
    end
    collection do
      get "index"
      get "info_type"
      get "contact"
      get "faq"
      get "privacy_policy"
      get "map"
      post "contact_confirm"
      post "send_contact"
    end
  end
  namespace :admin do
    resources :home, only: [:index] do

    end
    resources :prefectures do
      member do
        post "confirm_delete"
      end
    end
  end
  #adminメニュー
  resources :admin do
    member do
      post "confirm_delete_city"
      get "edit_city"
      post "update_city"
      post "delete_city"
      get "edit_office"
      post "confirm_office"
      post "update_office"
      post "delete_office_confirm"
      post "delete_office"
      get "edit_bedtype"
      post "update_bedtype"
      post "delete_bedtype"
      post "confirm_delete_bedtype"
      post "delete_uaccount_confirm"
      post "delete_uaccount"
      get "reserve_show"
    end
    collection do
      get "new_city"
      post "new_city_update"
      get "city_index"
      get "info_delete"
      get "new_bedtype"
      post "new_bedtype_update"
      get "bedtype_index"
      get "uaccount_index"
      get "mail_all_send"
      post "mail_all_send_confirm"
      post "all_uaccounts_send"
      get "reserves_index"
    end
  end
end

app/models/matter.rb
class Matter < ApplicationRecord
  enum end_reception_flg: { reception: 0, end_reception: 1}
  belongs_to :uaccount, optional: true
end

app/controllers/matters_controller.rb
class MattersController < ApplicationController
  before_action :authenticate_uaccount!
  before_action :get_matter,only: [:show, :edit, :edit_confirm, :destroy_confirm, :destroy, :update]
  before_action :build_matter, only: [:confirm, :create]
  before_action :check_uaccount, only: [:create, :update, :destroy]
  def index
    @matters=Matter.where(uaccount_id: current_uaccount.id, end_date: Date.today..Date.today.months_since(3)).order(start_date: "ASC").page(params[:page]).per(10)
  end
  def new
    @matter=Matter.new
    @matter.uaccount_id = current_uaccount.id
    @matter.end_reception_flg = "reception"
  end
  def confirm
    if @matter.start_date >= @matter.end_date
      flash.now[:notice] = "予約開始日と終了日の日付をご確認ください"
      render :new
    end
  end
  def create
    if Matter.create(update_params)
      flash[:notice] = "依頼ボードに登録されました"
      redirect_to matters_path
    else
      flash[:notice] = "依頼ボードに登録されませんでした"
      render :new
    end
  end

  def show
  end

  def edit
  end

  def edit_confirm
    @matter.assign_attributes(update_params)
    if @matter.start_date >= @matter.end_date
      flash[:notice] = "予約開始日と終了日の日付をご確認ください"
      render :edit
    end
  end
  def update
    if @matter.update(update_params)
      flash[:notice] = "予約が変更されました"
      redirect_to matters_path
    else
      flash[:notice] = "予約が変更できませんでした。#{@matter.errors.messages.values.join(",")}"
      render :edit
    end
  end
  def destroy_confirm
  end
  def destroy
    if @matter.destroy
      flash[:notice] = "予約が削除されました"
      redirect_to matters_path
    else
      flash[:notice] = "予約が削除されませんでした"
      redirect_to matters_path
    end
  end

private
  def get_matter
    @matter=Matter.find(params[:id])
  end
  def update_params
    params.require(:matter).permit(:uaccount_id, :start_date, :end_date, :remark, :end_reception_flg )
  end
  def check_uaccount
    if @matter.uaccount_id != current_uaccount.id
      flash[:notice] = "不正なアクセスです"
      render :new
      return
    end
  end
  def build_matter
    @matter = Matter.new(update_params)
  end
end

app/helpers/matters_helper.rb
module MattersHelper
end

app/views/matters/confirm.html.erb
<div id="main">

	<section>
		<%= form_with(model: @matter, url: matters_path, method: :post) do |f| %>
			<div class="button-modoru-box">
				<%= link_to "戻る", 'javascript:history.back()', method: :get, class: "button-modoru" %>
			</div>
			<table class="ta1">
				<tr>
					<th>ケアマネジャー</th>
					<td><%= f.hidden_field :uaccount_id %><% @matter.uaccount_id %><%= @matter.uaccount.user_name %></td>
				</tr>
				<tr>
					<th>開始日</th>
					<td><%= f.hidden_field :start_date %><%= @matter.start_date %></td>
				</tr>
				<tr>
					<th>終了日</th>
					<td><%= f.hidden_field :end_date %><%= @matter.end_date %></td>
				</tr>
				<tr>
					<th>ショートステイ依頼内容</th>
					<td><%= f.hidden_field :remark %><%= @matter.remark %></td>
				</tr>
			</table>
			<p class="c">
				<%= f.submit "依頼ボードに送信する", class:"btn" %>
			</p>
		<% end %>
	</section>

</div>
<!--/#main-->

app/views/matters/destroy_confirm.html.erb
<div id="main">

	<section>
		<%= form_with(model: @matter, url: matter_path, method: :DELETE) do |f| %>
			<div class="button-modoru-box">
				<%= link_to "戻る", 'javascript:history.back()', method: :get, class: "button-modoru" %>
			</div>
			<table class="ta1">
				<tr>
					<th>ケアマネジャー</th>
					<td><%= f.hidden_field :uaccount_id %><%= @matter.uaccount.user_name %></td>
				</tr>
				<tr>
					<th>開始日</th>
					<td><%= f.hidden_field :start_date %><%= @matter.start_date %></td>
				</tr>
				<tr>
					<th>終了日</th>
					<td><%= f.hidden_field :end_date %><%= @matter.end_date %></td>
				</tr>
				<tr>
					<th>ショートステイ依頼内容</th>
					<td><%= f.hidden_field :remark %><%= @matter.remark %></td>
				</tr>
			</table>
			<p class="c">
				<%= f.submit "依頼ボードに送信する", class:"btn" %>
			</p>
		<% end %>
	</section>

</div>
<!--/#main-->

app/views/matters/edit.html.erb
<div id="main">

	<section>
		<%= form_with(model: @matter, url: edit_confirm_matter_path, method: :post) do |f| %>
			<div class="button-modoru-box">
				<%= link_to "戻る", 'javascript:history.back()', method: :get, class: "button-modoru" %>
			</div>
			<table class="ta1">
				<tr>
					<th>ケアマネジャー</th>
					<td><%= f.hidden_field :uaccount_id %><% @matter.uaccount_id %> <%= @matter.uaccount.user_name %></td>
				</tr>
				<tr>
					<th>開始日</th>
					<td><%= f.date_field :start_date %><%= @matter.start_date %></td>
				</tr>
				<tr>
					<th>終了日</th>
					<td><%= f.date_field :end_date %><%= @matter.end_date %></td>
				</tr>
				<tr>
					<th>ショートステイ依頼内容</th>
					<td><%= f.text_area :remark, size: "30x5", class:"wl" %><%= @matter.remark %></td>
				</tr>
			</table>
			<p class="c">
				<%= f.submit "内容を確認する", class:"btn" %>
			</p>
		<% end %>
	</section>

</div>
<!--/#main-->

app/views/matters/edit_confirm.html.erb
<div id="main">

	<section>
		<%= form_with(model: @matter, url: matter_path, method: :PATCH) do |f| %>
			<div class="button-modoru-box">
				<%= link_to "戻る", 'javascript:history.back()', method: :get, class: "button-modoru" %>
			</div>
			<table class="ta1">
				<tr>
					<th>ケアマネジャー</th>
					<td><%= f.hidden_field :uaccount_id %><%= @matter.uaccount.user_name %></td>
				</tr>
				<tr>
					<th>開始日</th>
					<td><%= f.hidden_field :start_date %><%= @matter.start_date %></td>
				</tr>
				<tr>
					<th>終了日</th>
					<td><%= f.hidden_field :end_date %><%= @matter.end_date %></td>
				</tr>
				<tr>
					<th>ショートステイ依頼内容</th>
					<td><%= f.hidden_field :remark %><%= @matter.remark %></td>
				</tr>
			</table>
			<p class="c">
				<%= f.submit "依頼ボードに送信する", class:"btn" %>
			</p>
		<% end %>
	</section>

</div>
<!--/#main-->

app/views/matters/index.html.erb
<div id="main">

  <section>

    <h2>依頼内容一覧表</h2>
    <p>施設に依頼したいショートステイの案件を掲示板に載せます。</p>
    <p><%= link_to("新しい依頼", new_matter_path) %></p>

    <% @matters.each do |matter| %>
      <div class="list link">
        <div class="listinboxA">
          <h4>依頼番号<%= matter.id %>　<%= matter.uaccount.user_name %></h4>
          <p><%= link_to("予約期間#{matter.start_date}〜#{matter.end_date}", matter_path(matter.id),method: :GET) %></p>
          <p>概要：<%= matter.remark %></p>
          <div style="display:inline-block; margin-right: 10px;"><%= button_to("依頼を編集する", edit_matter_path(matter.id), class: "button-v1") %></div>
          <div style="display:inline-block;"><%= button_to("依頼を削除する", destroy_confirm_matter_path(matter.id), class: "button-v2") %></div>
        </div>
      </div>
    <% end %>
  <%= paginate @matters %>
  </section>

</div>
<!--/#main-->

app/views/matters/new.html.erb
<div id="main">

	<section>
		<%= form_with(model: @matter, url: confirm_matters_path, method: :post) do |f| %>
			<div class="button-modoru-box">
				<%= link_to "戻る", 'javascript:history.back()', method: :get, class: "button-modoru" %>
			</div>
			<table class="ta1">
				<tr>
					<th>ケアマネジャー</th>
					<td><%= f.hidden_field :uaccount_id %><%= @matter.uaccount.user_name %></td>
				</tr>
				<tr>
					<th>開始日</th>
					<td><%= f.date_field :start_date, size:10, class:"ws" %></td>
				</tr>
				<tr>
					<th>終了日</th>
					<td><%= f.date_field :end_date, size:10, class:"ws" %></td>
				</tr>
				<tr>
					<th>ショートステイ依頼内容</th>
					<td><%= f.text_area :remark, size: "30x5", class:"wl" %></td>
				</tr>
			</table>
			<p class="c">
				<%= f.submit "内容を確認する", class:"btn" %>
			</p>
		<% end %>
	</section>

</div>
<!--/#main-->

app/views/matters/show.html.erb
<div id="main">

	<section>
			<div class="button-modoru-box">
				<%= link_to "戻る", 'javascript:history.back()', method: :get, class: "button-modoru" %>
			</div>
			<table class="ta1">
				<tr>
					<th>ケアマネジャー</th>
					<td><%= @matter.uaccount.user_name %></td>
				</tr>
				<tr>
					<th>開始日</th>
					<td><%= @matter.start_date %></td>
				</tr>
				<tr>
					<th>終了日</th>
					<td><%= @matter.end_date %></td>
				</tr>
				<tr>
					<th>ショートステイ依頼内容</th>
					<td><%= @matter.remark %></td>
				</tr>
			</table>
	</section>

</div>
<!--/#main-->