config/routes.rb
Rails.application.routes.draw do
  devise_for :administrators, :controllers =>{
    :registrations => 'administrators/registrations',
    :sessions => 'administrators/sessions'
  }
  devise_scope :administrator do
    get "sign_in", :to => "administrators/sessions#new"
    get "sign_out", :to => "administrators/sessions#destroy"
  end

  get 'reserves/index'
  devise_for :oaccounts, :controllers =>{
    :registrations => 'oaccounts/registrations',
    :sessions => 'oaccounts/sessions'
  }
  devise_scope :oaccount do
    get "osign_in", :to => "oaccounts/sessions#new"
    get "osign_out", :to => "oaccounts/sessions#destroy"
  end
  namespace :oaccounts do
    resources :notices, only: [:index, :destroy]
  end

  devise_for :uaccounts, :controllers => {
    :registrations => 'uaccounts/registrations',
    :sessions => 'uaccounts/sessions'
  }
  devise_scope :uacoount do
    get "usign_in", :to => "uaccounts/sessions#new"
    get "usign_out", :to => "uaccounts/sessions#destroy"
  end

  namespace :uaccounts do
    resources :notices, only: [:index, :destroy]
  end
# usersメニュー　routing
  resources :users do
    member do
      post "confirm"
    end
  end
  # officesメニュー　routing
  resources :offices do
    member do
      post "confirm"
      post "find"
      get "bed_article"
      get "bed_article_edit"
      post "bed_article_confirm"
      post "bed_article_update"
    end
  end

  # reserves　メニューrouting
  resources :reserves do
    resources :comments, only: [:create, :destroy, :update]
    member do
      get "index"
      get "bed_show"
      get "reserve_show"
      get "comment_index"
      get "notice_index"
      post "delete_confirm"
      post "delete"
      post "edit"
      post "edit_confirm"
      post "edit_update"
    end
    collection do
      resources :favorites, only: [:create, :index] do
        collection do
          delete "destroy", as: :destroy
        end
      end
      get "service_date"
      get "permit_index"
      get "decline_index"
      get "history_index"
      get "favorite_index"
      get "info_type"
      post "confirm"
    end
  end
  resources :matters do
    member do
      post "edit_confirm"
      post "edit"
      post "destroy_confirm"
    end
    collection do
      post "confirm"
    end
  end
  resources :reserve_selves do
    resources :comments, only: [:create, :destroy, :update]
    member do
      get "decline_index"
      get "permit_index"
      get "history_index"
      get "comment_index"
      get "matter_index"
      get "matter_show"
      get "index"
      get "service_date"
      get "reserve_show"
      get "month_total"
      get "notice_index"
      post "permit_confirm"
      post "permit"
      post "decline_confirm"
      post "decline"
      post "decline_cancel_confirm"
      post "decline_cancel"
      post "cancel_confirm"
      post "cancel"
      post "edit"
      post "edit_confirm"
      post "edit_update"
    end
    collection do
      post "confirm"
    end
  end
  # mainメニュー　routing
  get "/", to:  "main#index", as: :root

  resources :main do
    member do
      get "show"
    end
    collection do
      get "index"
      get "info_type"
      get "contact"
      get "faq"
      get "privacy_policy"
      get "map"
      post "contact_confirm"
      post "send_contact"
    end
  end
  namespace :admin do
    resources :home, only: [:index] do

    end
    resources :prefectures do
      member do
        post "confirm_delete"
      end
    end
  end
  #adminメニュー
  resources :admin do
    member do
      post "confirm_delete_city"
      get "edit_city"
      post "update_city"
      post "delete_city"
      get "edit_office"
      post "confirm_office"
      post "update_office"
      post "delete_office_confirm"
      post "delete_office"
      get "edit_bedtype"
      post "update_bedtype"
      post "delete_bedtype"
      post "confirm_delete_bedtype"
      post "delete_uaccount_confirm"
      post "delete_uaccount"
      get "reserve_show"
    end
    collection do
      get "new_city"
      post "new_city_update"
      get "city_index"
      get "info_delete"
      get "new_bedtype"
      post "new_bedtype_update"
      get "bedtype_index"
      get "uaccount_index"
      get "mail_all_send"
      post "mail_all_send_confirm"
      post "all_uaccounts_send"
      get "reserves_index"
    end
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController
  before_action :authenticate_administrator!

  def index
  end
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/views/admin/home/index.html.erb
			<div id="main">

				<!--スライドショー-->
				<section>

					<h2>管理用画面です</h2>

					<h3>ショートステイ事業所の登録はこちらから入力してください</h3>
					<p><%= link_to("事業所の一覧及び修正・削除はこちら", info_delete_admin_index_path ) %></p>
          <p><%= link_to("新規事業所登録はこちら", new_oaccount_registration_path ) %></p>
          <p><%= link_to("ケアマネに一斉にメールを送信する", mail_all_send_admin_index_path ) %></p>

					<h3>ケアマネの編集及び削除はこちらから行ってください</h3>
					<p><%= link_to("ケアマネの一覧及び削除はこちら", uaccount_index_admin_index_path ) %></p>

					<h3>県の入力はこちらから入力してください</h3>
          <p><%= link_to("県の編集はこちら", admin_prefectures_path ) %></p>
					<p><%= link_to("県の新規追加はこちら", new_admin_prefecture_path ) %></p>

					<h3>市区町村の入力はこちらから入力してください</h3>
          <p><%= link_to("地区の編集はこちら", city_index_admin_index_path ) %></p>
          <p><%= link_to("地区の新規追加はこちら", new_city_admin_index_path ) %></p>

					<h3>ベッド種類の入力はこちらから入力してください</h3>
          <p><%= link_to("ベッド種類の編集はこちら", bedtype_index_admin_index_path ) %></p>
          <p><%= link_to("ベッド種類の新規追加はこちら", new_bedtype_admin_index_path ) %></p>

					<h3>全ての予約情報を確認する場合はこちら</h3>
          <p><%= link_to("予約情報の一覧はこちら", reserves_index_admin_index_path ) %></p>

				</section>


			</div>
			<!--/#main-->